# Generated by Django 4.1.5 on 2023-01-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttrali',
            old_name='p_id',
            new_name='id',
        ),
    ]
