# Generated by Django 4.0.5 on 2023-02-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop2app', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='data',
            new_name='date',
        ),
    ]
